#!/usr/bin/env python
"""Is the structured-baseline ratio an artefact of how the ratio was averaged?

WHY THIS EXISTS. tools/make_aggregation_robustness.py asks this of the headline
MLP comparison and finds the answer worth printing: the reported estimand is
systematically the LARGEST of the five defensible ones. Round-three review asked
the same question of Table 9.2 and was right to -- a ratio is a nonlinear
function of two means, E[X]/E[Y] is not E[X/Y], and the endpoints 2.3 and 6.1
have no claim on a reader's attention until they are shown not to move under a
different, equally defensible aggregation.

Nothing is refit. This reads the same frozen confirmatory CSV the table reads.

The estimands differ from the MLP appendix's because the cell structure differs.
exp_31 stores one row per (seed, size, method, region) with the noise schedule
already reduced into `risk` -- summed numerator and denominator, square-rooted
once -- so there is no per-noise-level estimand to form, and the seed is the unit
by construction rather than by an averaging choice. What remains genuinely
optional is how the ratio is formed and pooled:

    1. mean of per-seed ratios        (what the table reports)
    2. ratio of mean risks
    3. geometric mean of per-seed ratios
    4. median per-seed ratio
    5. paired bootstrap over seeds, 95%

    python tools/make_aggregation_structured.py

Writes overleaf/shared/sections/tab-aggregation-structured.tex. Do not hand-edit.
"""
import csv
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provenance_gate import load_params, require_clean  # noqa: E402

SOURCE_DIR = "outputs/frozen/exp_31_confirm_merged"
CSV = f"{SOURCE_DIR}/confirm.csv"
REGION = "all"  # the headline; the table it qualifies reports this one
BOOT = 20_000
RNG = np.random.default_rng(20260901)

with open(CSV) as fh:
    rows = [r for r in csv.DictReader(fh) if r["region"] == REGION]
if not rows:
    print(f"REFUSING: no region={REGION} rows at {CSV}", file=sys.stderr)
    sys.exit(1)

require_clean(load_params([SOURCE_DIR]))

seeds = sorted({r["seed"] for r in rows}, key=int)
sizes = sorted({int(r["n_chains"]) for r in rows})
F = lambda r, k: float(r[k])

lines, summary = [], {}
for n in sizes:
    em, wn = [], []
    for s in seeds:
        cell = [r for r in rows if r["seed"] == s and int(r["n_chains"]) == n]
        e = [F(r, "risk") for r in cell if r["method"] == "em_bp"]
        w = [F(r, "risk") for r in cell if r["method"] == "window"]
        assert len(e) == 1 and len(w) == 1, (s, n, e, w)
        em.append(e[0])
        wn.append(w[0])
    em, wn = np.array(em), np.array(wn)
    ratio = wn / em

    a1 = float(ratio.mean())
    a2 = float(wn.mean() / em.mean())
    a3 = float(np.exp(np.mean(np.log(ratio))))
    a4 = float(np.median(ratio))
    # Resamples SEEDS. The two arms within a seed share a training set, so the
    # pairing is the point and cells are not independent observations.
    idx = RNG.integers(0, ratio.size, (BOOT, ratio.size))
    lo, hi = np.percentile(ratio[idx].mean(axis=1), [2.5, 97.5])

    summary[n] = (a1, a2, a3, a4, lo, hi)
    lines.append(f"${n}$ & ${a1:.2f}$ & ${a2:.2f}$ & ${a3:.2f}$ & ${a4:.2f}$ & "
                 f"$[{lo:.2f},\\, {hi:.2f}]$ \\\\")

vals = np.array([[v[0], v[1], v[2], v[3]] for v in summary.values()])
spread = float(np.abs(vals - vals[:, [0]]).max())
smallest = float(vals.min())
reported_is_largest = bool(np.all(vals[:, 0] >= vals.max(axis=1) - 1e-12))

tex = f"""%% GENERATED by tools/make_aggregation_structured.py from {SOURCE_DIR}
%% (region={REGION}, {len(seeds)} seeds, {len(sizes)} sizes, provenance-clean).
%% Do not hand-edit the numbers; rerun the generator.

\\begin{{center}}
%% minipage, not a bare center: without it LaTeX will break between the
%% caption and the tabular, and it did -- Table 9.5's caption sat alone at
%% the foot of one page with its rows at the head of the next.
\\begin{{minipage}}{{\\linewidth}}\\small\\centering
\\captionof{{table}}{{Table~\\ref{{tab:structured}}'s all-site ratio under four
aggregations of the same cells, with the paired bootstrap interval over seeds.
(1) is what the table reports. The conclusion does not depend on the choice: no
estimand at any size falls below ${smallest:.2f}\\times$, and the largest
departure from the reported value is ${spread:.2f}$.}}
\\label{{tab:aggregation-structured}}
\\begin{{tabular}}{{rccccc}}
\\toprule
$\\nseq$ & (1) per-seed & (2) ratio of means & (3) geometric & (4) median & (5) 95\\% CI on (1) \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
\\end{{minipage}}
\\end{{center}}
"""

dest = "../../overleaf/shared/sections/tab-aggregation-structured.tex"
with open(dest, "w") as fh:
    fh.write(tex)
print(f"wrote {dest}")

# The floor was quoted in Chapter 9 and in the paper as "exceeds 2x". It is
# 1.98, so that sentence was false by a hair in exactly the direction that
# flatters the result. Exporting it removes the temptation to round.
macros = f"""%% GENERATED by tools/make_aggregation_structured.py -- do not hand-edit.
\\newcommand{{\\structaggfloor}}{{{smallest:.2f}}}
\\newcommand{{\\structaggspread}}{{{spread:.2f}}}
\\newcommand{{\\structaggcount}}{{{vals.shape[1]}}}
"""
mdest = "../../overleaf/shared/sections/structured-aggregation-numbers.tex"
with open(mdest, "w") as fh:
    fh.write(macros)
print(f"wrote {mdest}")
print(f"  source: {SOURCE_DIR} (region={REGION}, {len(seeds)} seeds)")
hdr = f"{'n':>6} {'(1) seed':>9} {'(2) means':>10} {'(3) geo':>8} {'(4) med':>8} {'(5) 95% CI':>18}"
print(hdr)
print("-" * len(hdr))
for n in sizes:
    a1, a2, a3, a4, lo, hi = summary[n]
    print(f"{n:>6} {a1:>9.2f} {a2:>10.2f} {a3:>8.2f} {a4:>8.2f} "
          f"{f'[{lo:.2f}, {hi:.2f}]':>18}")
print(f"\n  largest departure from the reported estimand: {spread:.2f}")
print(f"  every estimand at every size exceeds {smallest:.2f}x")
print(f"  reported estimand is the largest at every size: {reported_is_largest}")
