#!/usr/bin/env python
"""The architecture screen behind Table 9.2's baseline, shown rather than asserted.

WHY THIS EXISTS. Section 9.2 reports a ratio against "the winning structure-aware
architecture", and round-three review asked the obvious question: winning under
what search, and was the tuning effort comparable across the three candidates?
Stating the outcome is not the same as showing the screen. A reader who cannot
see the candidate grid, the parameter counts and the checkpoint ladder has no way
to judge whether the window head won on merit or on being the only arm that was
tuned properly.

It also caught a live error. The thesis, the paper's appendix and the compendium
all said the window head won "at radius 2". The selection rule the experiment
actually implements (`_winners_from_screening` in
experiments/exp_31_structured_baseline.py: mean risk over the development seeds,
scored on the BULK region) picks radius 4 at width 64. Radius 2 at width 64 is
third, 5.6% behind. The number had been read off the wrong aggregation and never
regenerated -- exactly the drift the "generated, not typed" rule exists to stop,
which is why the winner is emitted as a macro here rather than written in prose.

The parameter counts are the interesting disclosure. The dilated convolutional
stack carries 66k-264k parameters against the window head's 4.8k-21k, an order of
magnitude more, and finishes last. Whatever the screen failed to do, it did not
fail by starving the long-range architectures of capacity.

    python tools/make_tab_screening.py

Writes overleaf/shared/sections/tab-screening.tex and
overleaf/shared/sections/screening-numbers.tex. Do not hand-edit either.
"""
import csv
import json
import os
import sys
from collections import defaultdict

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provenance_gate import load_params, require_clean  # noqa: E402

SOURCE_DIR = "outputs/frozen/exp_31_screen"
CSV = f"{SOURCE_DIR}/screening.csv"

# The region the selection rule scores on. Not a free choice here: it has to
# match part_screen's, or this table would document a screen that never ran.
SELECTION_REGION = "bulk"

PRETTY = {
    "window": "weight-shared window head",
    "conv": "dilated convolutional stack",
    "bimp": "bidirectional message passing",
}
# Ordered as the chapter introduces them: the local one first, then the two
# built to propagate further.
ORDER = ("window", "conv", "bimp")

with open(CSV) as fh:
    rows = list(csv.DictReader(fh))
if not rows:
    print(f"REFUSING: no screening output at {CSV}", file=sys.stderr)
    sys.exit(1)

require_clean(load_params([SOURCE_DIR]))

params = json.loads(open(f"{SOURCE_DIR}/params_screen.json").read())

archs = sorted({r["arch"] for r in rows})
if set(archs) != set(ORDER):
    print(f"REFUSING: expected architectures {sorted(ORDER)}, got {archs} -- "
          "the screen's candidate set changed; update this generator before "
          "trusting its output.", file=sys.stderr)
    sys.exit(1)

dev_seeds = sorted({int(r["seed"]) for r in rows})
sizes = sorted({int(r["n_chains"]) for r in rows})
regions = sorted({r["region"] for r in rows})

# Mean risk per (arch, hp) over every development seed and size, on the
# selection region. This reproduces _winners_from_screening exactly; if it ever
# stops doing so, the table below documents a screen that did not happen.
scored = defaultdict(list)
for r in rows:
    if r["region"] == SELECTION_REGION:
        scored[(r["arch"], r["hp"])].append(float(r["risk"]))
ranked = sorted((float(np.mean(v)), k) for k, v in scored.items())

best_per_arch, n_configs, params_range = {}, {}, {}
for risk, (arch, hp) in ranked:
    best_per_arch.setdefault(arch, (risk, hp))
for arch in ORDER:
    n_configs[arch] = len({r["hp"] for r in rows if r["arch"] == arch})
    p = sorted({int(r["n_params"]) for r in rows if r["arch"] == arch})
    params_range[arch] = (p[0], p[-1])

winner_arch, winner_hp = ranked[0][1]
winner_risk = ranked[0][0]
winner = json.loads(winner_hp)
runner_up = next(r for r in ranked if r[1][0] != winner_arch)

checkpoints = sorted({int(r["checkpoint"]) for r in rows})
lrs = sorted({json.loads(r["hp"])["lr"] for r in rows})
modes = sorted({json.loads(r["hp"])["parameterization"] for r in rows})


def _fmt_params(lo, hi):
    f = lambda v: f"{v/1000:.1f}k" if v < 100_000 else f"{v/1000:.0f}k"
    return f"{f(lo)}--{f(hi)}"


lines = []
for arch in ORDER:
    risk, hp = best_per_arch[arch]
    lo, hi = params_range[arch]
    mark = r"\;$\star$" if arch == winner_arch else ""
    lines.append(
        f"{PRETTY[arch]}{mark} & {n_configs[arch]} & {_fmt_params(lo, hi)} & "
        f"${risk:.3f}$ \\\\"
    )

tex = f"""%% GENERATED by tools/make_tab_screening.py from {SOURCE_DIR}
%% ({len(dev_seeds)} development seeds, {len(rows)} scored rows, provenance-clean).
%% Do not hand-edit the numbers; rerun the generator.

\\begin{{center}}\\small
\\captionof{{table}}{{The architecture screen that selected Table~\\ref{{tab:structured}}'s
baseline. Each candidate architecture was run over its own hyperparameter grid on
{len(dev_seeds)} development seeds (disjoint from the confirmatory seeds),
at $\\nseq \\in \\{{{', '.join(str(s) for s in sizes)}\\}}$, with a shared learning-rate grid,
both output parameterisations, and a shared checkpoint ladder; the reported risk is
the mean over development seeds on the interior slice used for selection. $\\star$
marks the winner carried into the confirmatory run. The dilated stack carries an
order of magnitude more parameters than the winner and finishes last, so the
outcome is not an artefact of one arm being given more capacity than another.}}
\\label{{tab:screening}}
\\begin{{tabular}}{{lccc}}
\\toprule
architecture & configurations & parameters & selection risk \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
\\end{{center}}
"""

macros = f"""%% GENERATED by tools/make_tab_screening.py -- do not hand-edit.
%%
%% The prose cites these and never types the numbers. The radius below is the
%% reason why: it was typed once as 2, from the wrong aggregation, and stood in
%% three documents until this generator was written.
\\newcommand{{\\screenwinnerradius}}{{{winner['radius']}}}
\\newcommand{{\\screenwinnerwidth}}{{{winner['width']}}}
\\newcommand{{\\screenwinnerlr}}{{{winner['lr']:g}}}
\\newcommand{{\\screenwinnermode}}{{{winner['parameterization']}}}
\\newcommand{{\\screenwinnerrisk}}{{{winner_risk:.3f}}}
\\newcommand{{\\screenrunnerup}}{{{PRETTY[runner_up[1][0]]}}}
\\newcommand{{\\screenrunneruprisk}}{{{runner_up[0]:.3f}}}
\\newcommand{{\\screendevseeds}}{{{len(dev_seeds)}}}
\\newcommand{{\\screenconfigs}}{{{sum(n_configs.values())}}}
\\newcommand{{\\screenrows}}{{{len(rows)}}}
\\newcommand{{\\screenregion}}{{{SELECTION_REGION}}}
\\newcommand{{\\screenckptlo}}{{{checkpoints[0]}}}
\\newcommand{{\\screenckpthi}}{{{checkpoints[-1]}}}
\\newcommand{{\\screenlrs}}{{{', '.join(f'{v:g}' for v in lrs)}}}
%% Parameter counts, for the "was the tuning effort equal" question: the dilated
%% stack carries the most parameters of the three and finishes last.
\\newcommand{{\\screenwindowparams}}{{{_fmt_params(*params_range['window'])}}}
\\newcommand{{\\screenconvparams}}{{{_fmt_params(*params_range['conv'])}}}
\\newcommand{{\\screenbimpparams}}{{{_fmt_params(*params_range['bimp'])}}}
"""

for path, blob in (
    ("../../overleaf/shared/sections/tab-screening.tex", tex),
    ("../../overleaf/shared/sections/screening-numbers.tex", macros),
):
    with open(path, "w") as fh:
        fh.write(blob)
    print(f"wrote {path}")

print(f"  source: {SOURCE_DIR} (provenance-clean, {len(rows)} rows, "
      f"{len(dev_seeds)} dev seeds {dev_seeds})")
print(f"  selection region: {SELECTION_REGION}; regions present: {regions}")
print(f"  WINNER: {winner_arch} {winner_hp}  risk {winner_risk:.5f}")
for arch in ORDER:
    risk, hp = best_per_arch[arch]
    print(f"    {arch:7} best {risk:.5f}  {hp}  "
          f"({n_configs[arch]} configs, {_fmt_params(*params_range[arch])} params)")
print(f"  lr grid {lrs}, parameterisations {modes}, "
      f"checkpoints {checkpoints[0]}..{checkpoints[-1]}")
