#!/usr/bin/env python
"""The transition-Hellinger table: generated, clean-deployed, and weighted.

WHY THIS REPLACES THE HAND-TYPED TABLE IN app:hellinger
---------------------------------------------------------
Two defects, both closed by this generator reading a real run instead of
someone typing seven numbers into a LaTeX table:

1. The appendix's `transition Hellinger` row (0.100, 0.090, ..., 0.050) was
   HAND-TYPED, unlike every other headline number in this paper, which is why
   check_paper.sh's "no hand-typed efficiency ratio ranges" check could not
   catch it -- that check only looks at the efficiency table's own macros.
2. It was the UNWEIGHTED median over grid columns (round-two review,
   "Hellinger" section) -- one vote per parent grid point regardless of how
   much posterior mass ever lands there. `src/metrics.py` now also reports
   `hellinger_weighted_mean`, under the parent law shared by every family
   here (Var(a_i)=1), and this table reports both.

The source is outputs/exp_07_certified_clean_seed*/ -- the certified table
rerun through hpc/deploy_clean.sh (job 634911, all 16 seeds, 0 dirty paths;
outputs/README_exp07_certified_clean.md has the reproducibility check against
the original frozen run: 1344/1344 cells, zero difference). Gated through
provenance_gate.require_clean, so a future rerun that is NOT clean fails the
build instead of silently regenerating a table nobody can reconstruct --
which is exactly the defect this generator exists to not repeat.

    python tools/make_tab_hellinger.py

Writes overleaf/shared/sections/tab-hellinger.tex. Do not hand-edit it.
"""
from __future__ import annotations

import csv
import glob
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provenance_gate import load_params, require_clean  # noqa: E402

SOURCE = "outputs/exp_07_certified_clean_seed*/sample_efficiency_val.csv"
SOURCE_DIRS = glob.glob("outputs/exp_07_certified_clean_seed*")

if not SOURCE_DIRS:
    print(f"REFUSING: nothing at {SOURCE}", file=sys.stderr)
    sys.exit(1)

require_clean(load_params(SOURCE_DIRS))

rows = []
for f in sorted(glob.glob(SOURCE)):
    seed = f.split("seed")[1].split("/")[0]
    with open(f) as fh:
        for r in csv.DictReader(fh):
            r["seed"] = seed
            rows.append(r)

sizes = sorted({int(r["n_chains"]) for r in rows})
seeds = sorted({r["seed"] for r in rows}, key=int)
F = lambda r, k: float(r[k])  # noqa: E731


def per_seed_mean(g, key):
    return float(np.mean([
        np.mean([F(r, key) for r in g if r["seed"] == s])
        for s in seeds if any(r["seed"] == s for r in g)
    ]))


score_row, unweighted_row, weighted_row = [], [], []
for n in sizes:
    g = [r for r in rows if int(r["n_chains"]) == n]
    score_row.append(per_seed_mean(g, "em_bp_score_rel_l2"))
    unweighted_row.append(per_seed_mean(g, "em_hellinger"))
    weighted_row.append(per_seed_mean(g, "em_hellinger_weighted"))

n_seq_cols = " & ".join(f"${n}$" for n in sizes)
score_cols = " & ".join(f"${v:.4f}$" for v in score_row)
unw_cols = " & ".join(f"${v:.4f}$" for v in unweighted_row)
w_cols = " & ".join(f"${v:.4f}$" for v in weighted_row)

tex = f"""%% GENERATED by tools/make_tab_hellinger.py -- do not hand-edit.
%% Source: outputs/exp_07_certified_clean_seed*/ ({len(seeds)} seeds, clean
%% deploy, verified bit-identical to outputs/frozen/exp_07_certified_seed*/
%% on every score-based field -- see outputs/README_exp07_certified_clean.md.

\\begin{{center}}\\small
\\begin{{tabular}}{{@{{}}lccccccc@{{}}}}
\\toprule
$\\nseq$ & {n_seq_cols} \\\\
\\midrule
relative score error & {score_cols} \\\\
transition Hellinger (unweighted median) & {unw_cols} \\\\
transition Hellinger (parent-law-weighted mean) & {w_cols} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{center}}
"""

dest = "../../overleaf/shared/sections/tab-hellinger.tex"
with open(dest, "w") as fh:
    fh.write(tex)
print(f"wrote {dest}: {len(seeds)} seeds, sizes {sizes}")
print(f"  unweighted: {[f'{v:.4f}' for v in unweighted_row]}")
print(f"  weighted:   {[f'{v:.4f}' for v in weighted_row]}")
