import json

d = json.load(open("figdata.json"))
traj, st = d["traj"], d["stats"]
NSHOW, PW, GAP, X0, YTOP = 4, 138.0, 16.0, 40.0, 66.0
RANGE = 2.35
SC = PW / (2 * RANGE)

panels = [
    ("data", "(a) data", "#1D9E75"),
    ("walk", "(b) after gauge U", "#1D9E75"),
    ("joint", "(c) joint score", "#7F77DD"),
    ("marginal", "(d) marginal score", "#D85A30"),
]
foot = {
    "data": f"R = {st['data']['turn_concentration']:.2f}",
    "walk": "psi removed exactly",
    "joint": f"R = {st['joint']['turn_concentration']:.2f}",
    "marginal": f"R = {st['marginal']['turn_concentration']:.2f}",
}

out = []
A = out.append
H = 338
A(f'<svg width="100%" viewBox="0 0 680 {H}" role="img">')
A('<title>Joint versus marginal score on the rotating ring model</title>')
A('<desc>Four planar panels. Panel a shows four data trajectories spiralling '
  'coherently around the unit circle. Panel b shows the same trajectories '
  'after the orthogonal gauge, now plain random walks starting on the circle. '
  'Panel c, generated by the reverse diffusion driven by the exact joint '
  'score, reproduces the coherent rotation with turning concentration 0.94. '
  'Panel d, driven by per-frame marginal scores, has correct radii but '
  'turning concentration 0.01, that is no rotation at all.</desc>')
A('<defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" '
  'markerWidth="6" markerHeight="6" orient="auto-start-reverse">'
  '<path d="M2 1L8 5L2 9" fill="none" stroke="context-stroke" '
  'stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>'
  '</marker></defs>')

A(f'<text class="th" x="40" y="26">Same data, two score objects '
  f'(T = {st["params"]["T"]} frames, D = {st["params"]["D"]})</text>')
A('<text class="ts" x="40" y="44">R = concentration of the per-step turning '
  f'angle; the true rotation is psi = {st["psi_deg"]:.0f} degrees</text>')

for i, (key, title, col) in enumerate(panels):
    px = X0 + i * (PW + GAP)
    cx, cy = px + PW / 2, YTOP + PW / 2
    A(f'<rect class="box" x="{px:.1f}" y="{YTOP:.1f}" width="{PW:.1f}" '
      f'height="{PW:.1f}" rx="4"/>')
    A(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{SC:.1f}" fill="none" '
      f'stroke="var(--b)" stroke-width="0.5" stroke-dasharray="3 3"/>')
    for tr in traj[key][:NSHOW]:
        pts = " ".join(f"{cx + x * SC:.1f},{cy - y * SC:.1f}" for x, y in tr)
        A(f'<polyline points="{pts}" fill="none" stroke="{col}" '
          f'stroke-width="1.1" stroke-linejoin="round" opacity="0.85"/>')
        x0, y0 = tr[0]
        A(f'<circle cx="{cx + x0 * SC:.1f}" cy="{cy - y0 * SC:.1f}" r="2.2" '
          f'fill="{col}"/>')
    A(f'<text class="th" x="{px:.1f}" y="{YTOP + PW + 20:.1f}">{title}</text>')
    A(f'<text class="ts" x="{px:.1f}" y="{YTOP + PW + 37:.1f}">{foot[key]}</text>')

yb = YTOP + PW + 62
A(f'<rect class="box" x="40" y="{yb:.1f}" width="600" height="52" rx="4"/>')
A(f'<text class="t" x="56" y="{yb + 21:.1f}">Panel d matches every '
  'single-frame statistic of the data and has no dynamics at all.</text>')
A(f'<text class="ts" x="56" y="{yb + 39:.1f}">Mean radius per frame agrees '
  'with the data to 1.3 percent; the turning angle is uniform. Radii are '
  'not evidence.</text>')
A('</svg>')
open("fig.svg", "w").write("\n".join(out))
print("\n".join(out))
