#!/usr/bin/env bash
# Assemble overleaf-handover/ -- the four documents in one flat folder that
# Overleaf can compile as a single project.
#
# WHY THIS IS A SCRIPT AND NOT A ONE-OFF COPY
# The four documents share material: the setup section, the two propositions,
# the blindness theorem, the efficiency table, the notation file, the figures
# and the bibliography. Duplicating those by hand is how the documents came to
# disagree with each other in the first place. This script has one rule for
# where each shared file comes from, so a change lands in all four or in none.
#
# LAYOUT PRODUCED
#   paper.tex workshop.tex compendium.tex thesis.tex   the four roots
#   notation.tex preamble-thesis.tex neurips_2023.sty  preambles
#   references.bib                                     merged, see below
#   sections/       shared by paper and workshop
#   compendium/     compendium chapters
#   thesis-chapters/ thesis chapters and appendices
#   figures/        flattened union
#
# THE BIBLIOGRAPHY MERGE
# paper/bibliography.bib and thesis/references.bib share 14 keys for the same
# works, formatted differently -- the paper's carry eprint/archivePrefix and
# DOIs, the thesis's carry a bare note field. The paper's entry wins on a key
# clash, which is why the order below is paper first. Anything else would
# silently downgrade the metadata on the group's own references.
#
# Usage:  tools/make_handover.sh          rebuild the folder
#         tools/make_handover.sh --check  report drift, change nothing
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NB="$ROOT/research/nongaussian-bp"
OUT="$ROOT/overleaf-handover"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ "$CHECK" = 1 ]; then
    [ -d "$OUT" ] || { echo "no handover folder yet; run without --check"; exit 1; }
    TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
    OUT_REAL="$OUT"; OUT="$TMP/overleaf-handover"
fi

rm -rf "$OUT"
mkdir -p "$OUT/sections" "$OUT/compendium" "$OUT/thesis-chapters" "$OUT/figures"

# ---- the folder's own README and build script ----------------------------
# These live in the repo rather than only in the generated folder, because this
# script starts with `rm -rf $OUT` -- anything that exists only there is lost on
# the first rebuild, which is what happened to both of these once already.
cp "$ROOT/tools/handover-assets/README.md" "$OUT/README.md"
cp "$ROOT/tools/handover-assets/build.sh"  "$OUT/build.sh"
chmod +x "$OUT/build.sh"

# ---- shared preamble material -------------------------------------------
cp "$NB/paper/notation.tex"      "$OUT/notation.tex"
cp "$NB/paper/neurips_2023.sty"  "$OUT/neurips_2023.sty"
cp "$ROOT/thesis/preamble.tex"   "$OUT/preamble-thesis.tex"

# ---- shared sections, and the paper's appendix ---------------------------
cp "$NB/paper/sections/"*.tex "$OUT/sections/"
cp "$NB/paper/appendix.tex"   "$OUT/appendix.tex"

# ---- chapters, minus the archived ones -----------------------------------
# _superseded/ is deliberately excluded: those chapters were replaced and are
# kept in the repo only so the rewrite is auditable. Shipping them would put
# three retired versions of the background chapter in front of a reader.
find "$NB/compendium/chapters" -maxdepth 1 -name '*.tex' -exec cp {} "$OUT/compendium/" \;
find "$ROOT/thesis/chapters"   -maxdepth 1 -name '*.tex' -exec cp {} "$OUT/thesis-chapters/" \;

# ---- figures: union, flattened -------------------------------------------
# The five basenames present in both trees are byte-identical, so a flat
# directory loses nothing. If that ever stops being true this must fail rather
# than let one document silently render another's figure.
for f in "$NB/paper/figures/"*.pdf "$ROOT/thesis/figures/"*.pdf; do
    [ -e "$f" ] || continue
    dest="$OUT/figures/$(basename "$f")"
    if [ -e "$dest" ] && ! cmp -s "$f" "$dest"; then
        echo "FATAL: two different figures share the name $(basename "$f")" >&2
        exit 1
    fi
    cp "$f" "$dest"
done

# ---- merged bibliography --------------------------------------------------
{
    echo "% Generated by tools/make_handover.sh -- do not edit here."
    echo "% Sources: research/nongaussian-bp/paper/bibliography.bib (wins on key"
    echo "% clashes, it has the eprint and doi fields) then thesis/references.bib."
    cat "$NB/paper/bibliography.bib"
    echo
    cat "$ROOT/thesis/references.bib"
} > "$OUT/references.bib.raw"
"$NB/.venv/bin/python" - "$OUT/references.bib.raw" "$OUT/references.bib" <<'PY'
import re, sys
raw, dest = sys.argv[1], sys.argv[2]
txt = open(raw, encoding="utf-8").read()
head = txt[:txt.index("@")]
starts = [m.start() for m in re.finditer(r"^@", txt, re.M)]
seen, kept, dropped = {}, [], 0
for i, s in enumerate(starts):
    blk = txt[s:starts[i+1] if i+1 < len(starts) else len(txt)].strip()
    m = re.match(r"@\w+\{([^,]+),", blk)
    if not m:
        continue
    key = m.group(1).strip()
    if key in seen:          # first wins, and the paper's file is concatenated first
        dropped += 1
        continue
    seen[key] = True
    kept.append(blk)
open(dest, "w", encoding="utf-8").write(head + "\n\n".join(kept) + "\n")
print(f"  bibliography: {len(kept)} entries, {dropped} duplicate keys dropped")
PY
rm -f "$OUT/references.bib.raw"

# ---- the four roots, with their paths rewritten for a flat project --------
# sed, not hand-editing, so the rewrite is the same every time and a changed
# root upstream cannot quietly ship with a stale path.
sed -e 's|\\bibliography{bibliography}|\\bibliography{references}|' \
    "$NB/paper/main.tex" > "$OUT/paper.tex"

sed -e 's|\\bibliography{bibliography}|\\bibliography{references}|' \
    "$NB/paper/workshop.tex" > "$OUT/workshop.tex"

sed -e 's|\\graphicspath{{../paper/figures/}}|\\graphicspath{{figures/}}|' \
    -e 's|\\input{../paper/notation}|\\input{notation}|' \
    -e 's|\\bibliography{../paper/bibliography}|\\bibliography{references}|' \
    -e 's|\\input{chapters/|\\input{compendium/|' \
    -e 's|\.\./paper/notation\.tex|notation.tex|' \
    "$NB/compendium/main.tex" > "$OUT/compendium.tex"

sed -e 's|\\input{preamble}|\\input{preamble-thesis}|' \
    -e 's|\\input{chapters/|\\input{thesis-chapters/|' \
    "$ROOT/thesis/main.tex" > "$OUT/thesis.tex"

# ---- guard: no path may point outside the folder -------------------------
# Only the commands that actually resolve a path. A bare `../` is not enough to
# match on: the appendix typesets literal `exp_01_.../grid_heatmap.csv` strings
# for the reader, and a guard that fired on those would be turned off.
if grep -rnE '\\(input|include|includegraphics|bibliography|graphicspath|lstinputlisting)\s*(\[[^]]*\])?\{+\.\./' \
        "$OUT"/*.tex "$OUT"/sections/*.tex "$OUT"/compendium/*.tex \
        "$OUT"/thesis-chapters/*.tex 2>/dev/null; then
    echo "FATAL: a document still resolves a path outside the folder" >&2
    exit 1
fi

if [ "$CHECK" = 1 ]; then
    # Build products are not drift. Without these exclusions the report is
    # dozens of .aux/.bbl/.toc lines and the one .tex that actually diverged is
    # invisible in the noise, which is how a check stops being read.
    EX=(--exclude='*.pdf' --exclude='*.aux' --exclude='*.bbl' --exclude='*.blg'
        --exclude='*.out' --exclude='*.toc' --exclude='*.log' --exclude='*.lof'
        --exclude='*.lot' --exclude='*.xdv' --exclude='*.fls'
        --exclude='*.fdb_latexmk')
    if diff -rq "${EX[@]}" "$OUT_REAL" "$OUT" > /dev/null 2>&1; then
        echo "handover folder is in sync with the repo"
    else
        echo "DRIFT between repo and handover folder:"
        diff -rq "${EX[@]}" "$OUT_REAL" "$OUT" | sed 's/^/  /' || true
        echo
        echo "Rebuild with tools/make_handover.sh to take the repo's version,"
        echo "or copy the handover's version back to the repo source first."
        exit 1
    fi
else
    echo "handover folder written to $OUT"
    ls "$OUT"/*.tex | xargs -n1 basename | sed 's/^/  /'
fi
